spring:
  datasource:
    url: jdbc:mysql://118.24.61.199:3306/log-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: xzg
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
#  redis:
#    host: localhost
#    port: 6379
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cmiov.framework.logcenter.entity
  global-config:
    db-config:
      id-type: auto
logging:
  config: classpath:logback-spring.xml