spring:
  cloud:
    consul:
      host: localhost
      port: 8500
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
oauth2:
  token:
    renew:
      #是否开启token自动续签（redis实现）
      enable: true
      #续签时间比，
      timeRatio: 0.5
#      #白名单
#      includeClientIds:
#      - webApp
security:
  code:
    # 忽略验证码的应用编号
    ignoreClientCode: app