spring:
  datasource:
    druid:
      url: jdbc:mysql://118.24.61.199:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: xzg
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
user:
  application:
    name: user-center
oauth2:
  token:
    renew:
      #是否开启token自动续签（redis实现）
      enable: true
      #续签时间比，
      timeRatio: 0.5
#      #白名单
#      includeClientIds:
#      - webApp
security:
  code:
    # 忽略验证码的应用编号
    ignoreClientCode: app
logging:
  config: classpath:logback-spring.xml