spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: user
          uri: lb://user-center
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/api-auth/**
          filters:
            - StripPrefix=1
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  redis:
    host: localhost
    port: 6379
  main:
   allow-bean-definition-overriding: true
oauth2:
  token:
    store:
      type: redis
security:
  ignore:
    # 忽略认证的地址
    httpUrls: >
      /gateway/serialNum,
      /api-auth/oauth/**,
      /api-auth/validata/**,
      /api-user/users-anon/**,
      /login.html,
      /user/login
  auth:
    urlPermission:
      #是否开启url级别权限
      enable: true
      #配置只进行登录认证，不进行url权限认证的api
      ignoreUrls: >
        /api-user/menus/current,
        /api-user/users/current,
        /api-log/requestStat,
        /api-auth/validata/
      #白名单
      includeClientIds:
        - webApp
    renew:
      #是否开启token自动续签（目前只有redis实现）
      enable: true
      #白名单
      includeClientIds:
        - webApp
application:
  user:
    service: user-center
  log:
    service: log-center
cache-manager:
  configs:
    - key: all_menu
      second: 7200
    - key: role_menu
      second: 3600
gateway:
  #网关动态路由
  dynamicRoute:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
logging:
  config: classpath:logback-spring.xml