spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: user
          uri: lb://user-center
          predicates:
            - Path=/api-user/**
          filters:
            - StripPrefix=1
    consul:
      host: localhost
      port: 8500
  redis:
    host: localhost
    port: 6379
  main:
   allow-bean-definition-overriding: true
oauth2:
  token:
    store:
      type: redis
security:
  ignore:
    # 忽略认证的地址
    httpUrls: >
      /api-uaa/oauth/**,
      /api-uaa/validata/**,
      /api-uaa/css/**,
      /api-uaa/images/**,
      /api-uaa/js/**,
      /api-user/users-anon/**,
      /login.html,
      /user/login
  auth:
    urlPermission:
      #是否开启url级别权限
      enable: true
      #配置只进行登录认证，不进行url权限认证的api
      ignoreUrls: >
        /api-user/menus/current,
        /api-user/users/current,
        /api-log/requestStat
      #白名单
      includeClientIds:
        - webApp
    renew:
      #是否开启token自动续签（目前只有redis实现）
      enable: true
      #白名单
      includeClientIds:
        - webApp
gateway:
  #网关动态路由
  dynamicRoute:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000